### ISSUE TITLE
[1.11.2] Client crash

### ISSUE THREAD

**Issue by ruyanve** [GenuineSounds/WorldTooltip#12]
Was chopping a tree, falling wood showed the tooltip then I crashed...

log: https://gist.github.com/ruyanve/ee65613c1d85688ffa6ebcc9bf679447

I know I know, I have a shitton of coremods and stuff... I have been forced into making a kitchen sink pack, please don't jugde :(

Hope you're still supporting this as your mods have always been a personal favorite of mine! I'd love to see a comeback of closed captions, that was always fun!
Cheers mate

**Comment by GenuineSounds** [comment]
Just off a glance it's probably not anything to do with my mod specifically, I don't do anything crazy in terms of generating the tooltips, I let Minecraft (and Forge) handle essentially everything.

From what I can tell it was Minetweaker specifically, I'll look into it more in conjunction with Minetweaker when I get home from work tonight.

Thanks for the bug report, and I'll see what I can do to get Closed Captions working in later builds, from what I remember Forge changed some of the audio hooks and it made it a lot harder to determine whether a sound was from the same entity so there was a huge duplication bug in my mod. I'll test out some stuff when I get home.

**Comment by ruyanve** [comment]
Yeah I saw the Minetweaker reference, the thing is... I don't have Minetweaker installed. Since it's an api call I guess it's just shipped with another mod, but I don't know anything about Java, so that's the most uneducated guess you can get :-P

The only thing that really messes with tooltips would be: https://minecraft.curseforge.com/projects/mod-name-tooltip?gameCategorySlug=mc-mods&projectID=238747

If you need anything tested, let me know.
Anyway, I'm glad you're still around!
Cheers

**Comment by ruyanve** [comment]
God damnit I am stupid lately! I DO have Minetweaker installed!
