### ISSUE TITLE
[1.12.2] Not working on server?

### ISSUE THREAD

**Issue by Xiaminou** [GenuineSounds/WorldTooltip#20]
I can't seem to get this to work on my server, works fine in SSP, but nothing on the server, both sides have the mod (in case it's required). Am I missing something or is this a bug?

Minecraft: 1.12.2
Forge: 2641
Mods: [list.txt](https://github.com/GenuineSounds/World-Tooltips/files/1928093/list.txt)

**Comment by GenuineSounds** [comment]
It's probably my fault, I updated it to 1.12.2 and never checked to see if it would world for SMP worlds, thanks for the heads up.

EDIT: I'll work on it when I get home from work tonight.

**Comment by sumdream** [comment]
The same problem to me, Its does  work on server,but works fine in SSP.I am plugin server.

**Comment by GenuineSounds** [comment]
Finally got around to fixing Multiplayer, so sorry it took so long.

https://github.com/GenuineSounds/World-Tooltips/releases/tag/1.3.0

You can also find it on Curse.
