### ISSUE TITLE
Suggestion: More Config Options

### ISSUE THREAD

**Issue by IdrisQe** [GenuineSounds/WorldTooltip#21]
Hey! First of all thank you for the mod, it's a very cool concept and implementation!
However, I have some suggestions for new configuration options to increase customizability:

1. I:MaxTooltips=0|16+ (0 being no cap)
This would let you to set a cap of how many tooltips can be active for the client at once. If set to 2, for example, and three items on the ground were looked at, the first one would fade out the moment the 3rd appears, etc.
2. I:ShowTime=0|100+ (ticks)
This would allow customization of how long after looking away before a tooltip will fade.
3. I:FadeTime=0|100+ (ticks)
This would allow customization of how fast the tooltips fade after ShowTime's timer is up.

**Comment by GenuineSounds** [comment]
I'll work on all these tonight, so sorry for the wait.

**Comment by GenuineSounds** [comment]
Here is a working preview. Please use it and let me know what you think!

https://github.com/GenuineSounds/World-Tooltips/releases/tag/1.2.9

Please feel free to reopen this issue if any crashes occur with this release.

You may need to delete the config file for the mod if any duplicate options are showing, if you can simply ignore them entirely.

**Comment by GenuineSounds** [comment]
Newest version works on Multiplayer now as well.

https://github.com/GenuineSounds/World-Tooltips/releases/tag/1.3.0

You can also find it on Curse and Twitch.
