### ISSUE TITLE
Crash with Minecraft F3 profiler

### ISSUE THREAD

**Issue by Cazadorsniper** [GenuineSounds/WorldTooltip#24]
https://pastebin.com/mXLRtRFw

Can reproduce this crash by having the minecraft profiler open (shift + F3). (I also threw a few items on the ground.

**Comment by GenuineSounds** [comment]
Fixed, sorry for the wait, I'm updating it on Curse now.

**Comment by GenuineSounds** [comment]
This is now fixed in the 1.12 version of the mod.
