### ISSUE TITLE
[Request / Suggestion] Allow configurable hotkey

### ISSUE THREAD

**Issue by jd-ihm** [GenuineSounds/WorldTooltip#25]
Please allow users to specify which hotkey opens the configuration menu of the mod.

**Comment by GenuineSounds** [comment]
The key is configurable, it's in the standard controls menu. The default is the subtract button on the number pad.

**Comment by jd-ihm** [comment]
Where is the configuration set at because in game it cannot be located, I've checked both through the mod options menu and the keybinding menu.  Neither offers an option to change that hotkey from num pad -.

**Comment by GenuineSounds** [comment]
Can I ask which version you are using? MC version and Mod version. The keybinding is called "World Tooltips Configuration" and is sorted under "World Tooltips" in the controls settings.

![](https://i.imgur.com/e2iX2w4.png)

Let me know if I need to update an older version or something.

**Comment by jd-ihm** [comment]
I'll have to check what version it is, it's what is being used in the Project Ozone 3 pack that was just released last week.  I'll get you the details later, and awesome job on already having it in. I appreciate that.

**Comment by GenuineSounds** [comment]
New version works with Multiplayer now as well as some better fading options and smoother fading.

https://github.com/GenuineSounds/World-Tooltips/releases/tag/1.3.0

You can also find it on Curse/Twitch
