### ISSUE TITLE
[Suggestion] Alpha Transparency

### ISSUE THREAD

**Issue by ChloeDawn** [GenuineSounds/WorldTooltip#3]
**Config to adjust the alpha transparency of the tooltip background, similar to WAILA.**

**Comment by GenuineSounds** [comment]
I'll add that to the config for the moment while I work on adding a gui for the config. Thanks for the suggestion.

**Comment by GenuineSounds** [comment]
@InsomniaKitten Added with commit https://github.com/GenuineSounds/WorldTooltip/commit/6590993f68d2f7a6ef23e3a721cb8b74645d5551
