### ISSUE TITLE
[Bug/Suggestion?] Hide Mod Name When WAILA Is Active

### ISSUE THREAD

**Issue by ChloeDawn** [GenuineSounds/WorldTooltip#4]
Mod names double up when WAILA/HWYLA is installed. Maybe have the mod name display only when WAILA isn't present? Or.. Make the mod name a toggleable feature in the config. ^-^

I'd prefer to have it toggleable, as I typically play with the mod name hidden.

Example of doubled mod name with [HWYLA](https://github.com/TehNut/HWYLA):

![2016-12-14_22 00 10](https://cloud.githubusercontent.com/assets/9869940/21203154/26112762-c249-11e6-9a1e-ecf79cf9a129.png)

**Comment by GenuineSounds** [comment]
You're right, fixed with https://github.com/GenuineSounds/WorldTooltip/commit/f88e215ba90dc8e4f234cd5f8971b6c3eca127dc new build will be up in a minute.

**Comment by GenuineSounds** [comment]
Correctly fixed and tested with https://github.com/GenuineSounds/WorldTooltip/commit/a06ed210a99b62ad632379308c691ef7978a496a new builds will be up on Curse momentarily.
